"""Initial migration

Revision ID: 7bba9ea849b1
Revises: 087ae259bc7f
Create Date: 2025-05-20 00:22:25.826925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bba9ea849b1'
down_revision = '087ae259bc7f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
